providers:
  - name: PingdomMulti
    apiURL: "https://api.pingdom.com/v2/"
    apiKey: "657a68d9ashdyasjdklkskuasd"
    username: "user@test.com"
    password: "SuperSecret"
    accountEmail: "multi@test.com"
    alertContacts: "0544483_0_0-2628365_0_0-2633263_0_0"
    alertIntegrations: "91166,10924"
enableMonitorDeletion: true
